## Automobile Project
1. what is the average price and average mileage for convertible cars
2. Sort cars by company and price in decending order
3. Save data for 'Toyota' separately
4. which company is producing most expensive car?
5. Name the cars on basis of maximum horsepower
6. company wise average price of cars and order them in decending order
7. create a column named: "decision", If wheel-base is less than 100 and length is less than 175 then "don't buy" else "buy"
8. Select only cars whose decision is "buy"; find average price based on company of car

In [35]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv("Automobile_data.csv")

In [8]:
df

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
0,0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495.0
1,1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500.0
2,2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500.0
3,3,audi,sedan,99.8,176.6,ohc,four,102,24,13950.0
4,4,audi,sedan,99.4,176.6,ohc,five,115,18,17450.0
...,...,...,...,...,...,...,...,...,...,...
56,81,volkswagen,sedan,97.3,171.7,ohc,four,85,27,7975.0
57,82,volkswagen,sedan,97.3,171.7,ohc,four,52,37,7995.0
58,86,volkswagen,sedan,97.3,171.7,ohc,four,100,26,9995.0
59,87,volvo,sedan,104.3,188.8,ohc,four,114,23,12940.0
60,88,volvo,wagon,104.3,188.8,ohc,four,114,23,13415.0

In [9]:
df.head()

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
0,0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495.0
1,1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500.0
2,2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500.0
3,3,audi,sedan,99.8,176.6,ohc,four,102,24,13950.0
4,4,audi,sedan,99.4,176.6,ohc,five,115,18,17450.0

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   index             61 non-null     int64
 1   company           61 non-null     object
 2   body-style        61 non-null     object
 3   wheel-base        61 non-null     float64
 4   length            61 non-null     float64
 5   engine-type       61 non-null     object
 6   num-of-cylinders  61 non-null     object
 7   horsepower        61 non-null     int64
 8   average-mileage   61 non-null     int64
 9   price             58 non-null     float64
dtypes: float64(3), int64(3), object(4)
memory usage: 4.9+ KB

QUESTION 1

In [12]:
df['body-style'] == "convertible"

0      True
1      True
2     False
3     False
4     False
      ...
56    False
57    False
58    False
59    False
60    False
Name: body-style, Length: 61, dtype: bool

In [13]:
df[df['body-style'] == "convertible"]

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
0,0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495.0
1,1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500.0
46,62,porsche,convertible,89.5,168.9,ohcf,six,207,17,37028.0

In [14]:
df[df['body-style'] == "convertible"][["average-mileage","price"]]

    average-mileage    price
0                21  13495.0
1                21  16500.0
46               17  37028.0

In [15]:
df[df['body-style'] == "convertible"][["average-mileage","price"]].mean()

average-mileage       19.666667
price              22341.000000
dtype: float64

QUESTION 2

In [17]:
df.sort_values(by=['company','price'],ascending=False)

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
60,88,volvo,wagon,104.3,188.8,ohc,four,114,23,13415.0
59,87,volvo,sedan,104.3,188.8,ohc,four,114,23,12940.0
58,86,volkswagen,sedan,97.3,171.7,ohc,four,100,26,9995.0
57,82,volkswagen,sedan,97.3,171.7,ohc,four,52,37,7995.0
56,81,volkswagen,sedan,97.3,171.7,ohc,four,85,27,7975.0
...,...,...,...,...,...,...,...,...,...,...
5,5,audi,sedan,99.8,177.3,ohc,five,110,19,15250.0
3,3,audi,sedan,99.8,176.6,ohc,four,102,24,13950.0
1,1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500.0
2,2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500.0
0,0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495.0

QUESTION 3

In [20]:
df[df['company'] == "toyota"].to_csv("toyota data.csv")

QUESTION 4

In [24]:
df.sort_values(by='price' ,ascending=False).head(1)

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
35,47,mercedes-benz,hardtop,112.0,199.2,ohcv,eight,184,14,45400.0

In [27]:
df.sort_values(by='price' ,ascending=False).head(1)[['company','price']]

          company    price
35  mercedes-benz  45400.0

QUESTION 5

In [28]:
df.sort_values(by='horsepower' ,ascending=False).head(1)[['company','price']]

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
47,63,porsche,hatchback,98.4,175.7,dohcv,eight,288,17,NaN

In [30]:
df.sort_values(by='horsepower' ,ascending=False).head(1)[['company','horsepower']]

    company  horsepower
47  porsche         288

QUESTION 6

In [31]:
df.groupby('company')['price'].mean()

company
alfa-romero      15498.333333
audi             16392.500000
bmw              27213.333333
chevrolet         6007.000000
dodge             6303.000000
honda            10195.000000
isuzu             6785.000000
jaguar           34600.000000
mazda             9654.800000
mercedes-benz    35040.000000
mitsubishi        6689.000000
nissan            8289.000000
porsche          35528.000000
toyota            8216.857143
volkswagen        8435.000000
volvo            13177.500000
Name: price, dtype: float64

In [33]:
df.groupby('company')['price'].mean().round(0)

company
alfa-romero      15498.0
audi             16392.0
bmw              27213.0
chevrolet         6007.0
dodge             6303.0
honda            10195.0
isuzu             6785.0
jaguar           34600.0
mazda             9655.0
mercedes-benz    35040.0
mitsubishi        6689.0
nissan            8289.0
porsche          35528.0
toyota            8217.0
volkswagen        8435.0
volvo            13178.0
Name: price, dtype: float64

In [34]:
df.groupby('company')['price'].mean().round(0).sort_values(ascending=False)

company
porsche          35528.0
mercedes-benz    35040.0
jaguar           34600.0
bmw              27213.0
audi             16392.0
alfa-romero      15498.0
volvo            13178.0
honda            10195.0
mazda             9655.0
volkswagen        8435.0
nissan            8289.0
toyota            8217.0
isuzu             6785.0
mitsubishi        6689.0
dodge             6303.0
chevrolet         6007.0
Name: price, dtype: float64

QUESTION 7

In [36]:
# create a column named: "decision", If wheel-base is less than 100 and length is less than 175 then "don't buy" else "buy"

In [39]:
np.where((df['wheel-base']<100) & (df['length']<175), 'Dont buy','Buy')

array(['Dont buy', 'Dont buy', 'Dont buy', 'Buy', 'Buy', 'Buy', 'Buy',
       'Buy', 'Buy', 'Buy', 'Buy', 'Buy', 'Buy', 'Dont buy', 'Dont buy',
       'Dont buy', 'Dont buy', 'Dont buy', 'Dont buy', 'Buy', 'Dont buy',
       'Dont buy', 'Dont buy', 'Dont buy', 'Buy', 'Buy', 'Buy',
       'Dont buy', 'Dont buy', 'Dont buy', 'Dont buy', 'Buy', 'Buy',
       'Buy', 'Buy', 'Buy', 'Dont buy', 'Dont buy', 'Dont buy',
       'Dont buy', 'Dont buy', 'Dont buy', 'Dont buy', 'Dont buy', 'Buy',
       'Dont buy', 'Dont buy', 'Buy', 'Dont buy', 'Dont buy', 'Dont buy',
       'Dont buy', 'Dont buy', 'Dont buy', 'Buy', 'Dont buy', 'Dont buy',
       'Dont buy', 'Dont buy', 'Buy', 'Buy'], dtype='<U8')

In [40]:
df['decision'] = np.where((df['wheel-base']<100) & (df['length']<175), 'Dont buy','Buy')

In [41]:
df.head()

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price,decision
0,0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495.0,Dont buy
1,1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500.0,Dont buy
2,2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500.0,Dont buy
3,3,audi,sedan,99.8,176.6,ohc,four,102,24,13950.0,Buy
4,4,audi,sedan,99.4,176.6,ohc,five,115,18,17450.0,Buy

QUESTION 8

In [44]:
df[df['decision'] == 'Buy']

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price,decision
0,0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495.0,Buy
1,1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500.0,Buy
2,2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500.0,Buy
3,3,audi,sedan,99.8,176.6,ohc,four,102,24,13950.0,Buy
4,4,audi,sedan,99.4,176.6,ohc,five,115,18,17450.0,Buy
...,...,...,...,...,...,...,...,...,...,...,...
56,81,volkswagen,sedan,97.3,171.7,ohc,four,85,27,7975.0,Buy
57,82,volkswagen,sedan,97.3,171.7,ohc,four,52,37,7995.0,Buy
58,86,volkswagen,sedan,97.3,171.7,ohc,four,100,26,9995.0,Buy
59,87,volvo,sedan,104.3,188.8,ohc,four,114,23,12940.0,Buy
60,88,volvo,wagon,104.3,188.8,ohc,four,114,23,13415.0,Buy

In [46]:
df[df['decision'] == 'Buy'].groupby('company')['price'].mean()

company
alfa-romero      15498.333333
audi             16392.500000
bmw              27213.333333
chevrolet         6007.000000
dodge             6303.000000
honda            10195.000000
isuzu             6785.000000
jaguar           34600.000000
mazda             9654.800000
mercedes-benz    35040.000000
mitsubishi        6689.000000
nissan            8289.000000
porsche          35528.000000
toyota            8216.857143
volkswagen        8435.000000
volvo            13177.500000
Name: price, dtype: float64